image: node:14

services:
  - postgres:latest

variables:
  POSTGRES_DB: todos
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: postgres

before_script:
  - npm install
  - npm install -g sequelize-cli
  - npx sequelize-cli db:create
  - npx sequelize-cli db:migrate

stages:
  - test

test:
  stage: test
  script:
    - npm test
